/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DomComponent {
        "heading": string;
    }
    interface ShadowComponent {
        "heading": string;
    }
}
declare global {
    interface HTMLDomComponentElement extends Components.DomComponent, HTMLStencilElement {
    }
    var HTMLDomComponentElement: {
        prototype: HTMLDomComponentElement;
        new (): HTMLDomComponentElement;
    };
    interface HTMLShadowComponentElement extends Components.ShadowComponent, HTMLStencilElement {
    }
    var HTMLShadowComponentElement: {
        prototype: HTMLShadowComponentElement;
        new (): HTMLShadowComponentElement;
    };
    interface HTMLElementTagNameMap {
        "dom-component": HTMLDomComponentElement;
        "shadow-component": HTMLShadowComponentElement;
    }
}
declare namespace LocalJSX {
    interface DomComponent {
        "heading"?: string;
    }
    interface ShadowComponent {
        "heading"?: string;
    }
    interface IntrinsicElements {
        "dom-component": DomComponent;
        "shadow-component": ShadowComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dom-component": LocalJSX.DomComponent & JSXBase.HTMLAttributes<HTMLDomComponentElement>;
            "shadow-component": LocalJSX.ShadowComponent & JSXBase.HTMLAttributes<HTMLShadowComponentElement>;
        }
    }
}
